<a href="https://colab.research.google.com/github/kolithawarnakulasooriya/PyTorch-Learning/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

1. Tensors are the same representation like numpy. a multi dimensional single data type array.
2. The data type is float32, numpy is float64
3. easy to make operations with GPU level


In [ ]:
# python list
l = [[1,2,3,4,5], [6,7,8,9,10]]
l

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [ ]:
import numpy as np

l1 = np.zeros((2,3))
l2 = np.random.rand(3,4)

l1, l2

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[0.75290855, 0.77473556, 0.42930324, 0.46902793],
        [0.53594214, 0.32787736, 0.32407083, 0.14541373],
        [0.42915136, 0.09178172, 0.47735468, 0.01617994]]))

In [ ]:
import torch

l3 = torch.randn(2,5,3)
l3

tensor([[[ 0.4089,  0.0353, -1.4081],
         [-0.4630,  0.1586, -0.2465],
         [ 0.1985, -0.2030,  0.9900],
         [ 0.5375, -2.5154,  0.8733],
         [ 0.8647,  1.2629, -1.4677]],

        [[ 1.2457,  0.3813, -0.5941],
         [ 1.3345,  0.2446, -0.8881],
         [-0.1497,  0.5216,  1.3833],
         [-0.2911,  2.3419, -0.3089],
         [ 0.7902,  2.2655,  1.3051]]])